### PR TITLE
feat: added follow, bookmark, comment

### PR DESCRIPTION
**Pull request by AnjaliDeshwani**
Below features are implemented

- Added comment, bookmark
- Added explore page
- Added follow-unfollow and modified post feed as per following list
- Added  delete/edit comment option on single Post page

### CODE REVIEW

**Comment by saketkum11** [comment]
- UI looks great.
- some suggestion in follow and unfollow section --> after clicking on the follow button I  don't have option to unfollow the particular person. 
- in profile I am not able to open the follow link whom did I followed.
- if possible shot PR would be great.
- rest All Good .

**Comment by AnjaliDeshwani** [comment]
> * UI looks great.
> * some suggestion in follow and unfollow section --> after clicking on the follow button I  don't have option to unfollow the particular person.
> * in profile I am not able to open the follow link whom did I followed.
> * if possible shot PR would be great.
> * rest All Good .

Thanks for reviewing Saket, I will update these things in the next PR for User profile page.

**Review by saketkum11 — APPROVED** [review]
Good to go ahead

**Review by Pratik1005 — APPROVED** [review]
Functionality working properly, good to merge

**Pull request merged**
